imports:
    - { resource: parameters.yml }

framework:
    secret: %kernel.secret%
    assets: ~
    templating:
        engines: ['twig']

twig:
  globals:
    projects_title: %version_matrix.projects_title%
