parameters:
    version_matrix.loader.file.class: VersionMatrix\Loader\FileLoader
    version_matrix.loader.git.class: VersionMatrix\Loader\GitLoader
services:
  version_matrix.config.factory:
    class: AppBundle\Config\ConfigFactory
    arguments: ["@=container.hasParameter('version_matrix.projects') ? parameter('version_matrix.projects') : []"]
  version_matrix.analyzer:
    class: VersionMatrix\Analyzer\Analyzer
  version_matrix.matrix:
    class: VersionMatrix\VersionMatrix
    arguments: ["@=service('version_matrix.config.factory').getConfig()", "@version_matrix.analyzer"]